### ISSUE TITLE
Integration tests for GSModel tests fail

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-cdb10#37]
Several integration tests for methods beginning with **'VerifyGSModel...'** fail when running `mvn test`.

An extract from the output is below.

```
Results :

Failed tests: 
  VerifyGSModelInteriorDescriptorStructureTests.verifyGSModelInteriorDescriptorEntry_invalidLod 
Expected: (an instance of java.lang.AssertionError and exception with message a string containing "Invalid LOD name: L99")
     but: an instance of java.lang.AssertionError <java.nio.file.FileSystemException: /tmp/cdbTest-3507324510257371022/Tiles/N99/W162: Too many open files> is a java.nio.file.FileSystemException
Stacktrace was: java.nio.file.FileSystemException: /tmp/cdbTest-3507324510257371022/Tiles/N99/W162: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at org.opengis.cite.cdb10.cdbStructure.Capability1Tests.iterateEntries(Capability1Tests.java:114)
	at org.opengis.cite.cdb10.cdbStructure.Capability1Tests.iterateEntries(Capability1Tests.java:119)


```

**Comment by openfirmware** [comment]
I can't seem to reproduce this error. Which version of the JDK and Maven are you using?

**Comment by ghobona** [comment]
JDK 1.8.

In the interests of time, I have created a pre-release that [archives](https://github.com/opengeospatial/ets-cdb10/releases/tag/v0.4.1) the GSModel integration tests and then [deleted them](https://github.com/opengeospatial/ets-cdb10/pull/38) from the main branch of the repo.

We can bring the GSModel integration tests back at a later point in time, e.g. when we work on the CDB 1.1 test suite.

For now, we have what we need to proceed with the Beta release of the CDB 1.0 test suite.
